export const GET_ORDER_NUMBERS = "GET_ORDER_NUMBERS";
export const GET_EQUIPMENT_LIST = "GET_EQUIPMENT_LIST";
export const RESET_EQUIPMENT_LIST = "RESET_EQUIPMENT_LIST";
export const GET_DATA_FROM_DB = "GET_DATA_FROM_DB";
// new values
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_SERVER_CONFIG = "SET_SERVER_CONFIG";
export const SET_USER_LIST = "SET_USER_LIST";